### ISSUE TITLE
How to install one zookeeper operator per namespace?

### ISSUE THREAD

**Issue by krishnachalla-hv** [pravega/zookeeper-operator#292] opened 2021-01-17 10:58 UTC
In my current project we creating multi tenant application. For that I need to install zookeeper operator and solr operator per namespace. In the solr operator there is flag watchnamespaces: true then it will watch only that particular namespace. In zookeeper operator there is a same kind of flag but not working for me.
lets say I installed zookeeper operator for tenant-1 like below
helm install t0 banzaicloud-stable/zookeeper-operator -n tenant-1 --set watchnamespace=tenant-1
then again I tried to install in tenant-2 namespace
helm install t0 banzaicloud-stable/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2
getting the below error
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "zookeeperclusters.zookeeper.pravega.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "tenant-2": current value is "tenant-1"
Any help would be much appreciated. Thanks in advance.

**Comment by Prabhaker24** [comment] 2021-01-17 12:43
@krishnachalla-hv  This is because you are giving the same chart name i.e **t0** try installing the second zk-op with a different name.

**Comment by krishnachalla-hv** [comment] 2021-01-17 17:00
No Still the same error. 
`helm install t1 pravega/zookeeper-operator --set watchnamespace="tenant-2" -n tenant-2
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "zookeeperclusters.zookeeper.pravega.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "t1": current value is "t0"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "tenant-2": current value is "tenant-1"
`

**Comment by krishnachalla-hv** [comment] 2021-01-17 17:01
I am installing in another namespace I can use the same release name right?

**Comment by Prabhaker24** [comment] 2021-01-18 06:23
This error is happening as you already have installed crd with the first install for the second install please give the value of **crd.create* as **false** check the values.yaml file here *https://github.com/pravega/zookeeper-operator/blob/e393d1fba9b8d6110552c43ba688cec0dacd2c0d/charts/zookeeper-operator/values.yaml#L28, and it should work.

**Comment by Prabhaker24** [comment] 2021-01-18 06:24
> I am installing in another namespace I can use the same release name right?

I also always prefer to give a different helm release name. Have you tried giving the same release name in different ns has it worked for you?

**Comment by krishnachalla-hv** [comment] 2021-01-18 06:36
I am developing multi tenant application for each client I am planning to have zookeeper that will be local to to that namespace. If I install first zookeeper operator in **tenant-1** ns with **crd.create** as **true** and then in then in the **tenant-2** namespace if I say **crd.create** as **false** will this be local to **tenant-2** namespace?

I have installed [Solr Operator](https://github.com/apache/lucene-solr-operator) with the same release name in two different namespaces with **watchnamespaces** as **true** worked fine. I am expecting the same thing to happen here. That solr operator is relaying on this zookeeper operator.

**Comment by krishnachalla-hv** [comment] 2021-01-18 06:37
> > I am installing in another namespace I can use the same release name right?
> 
> I always prefer to give a different helm release name. Have you tried giving the same release name in different ns has it worked for you?

No it didn't work for me.

**Comment by Prabhaker24** [comment] 2021-01-18 06:47
> > > I am installing in another namespace I can use the same release name right?
> > 
> > 
> > I always prefer to give a different helm release name. Have you tried giving the same release name in different ns has it worked for you?
> 
> No it didn't work for me. Need to check with **crd.create** as **false** once.

Yes, please try with the false thing once and let me know you should run the command below for installing it:-

``` helm install t1 banzaicloud-stable/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2 --set crd.create=fasle ```

**Comment by krishnachalla-hv** [comment] 2021-01-18 06:54
> > > > I am installing in another namespace I can use the same release name right?
> > > 
> > > 
> > > I always prefer to give a different helm release name. Have you tried giving the same release name in different ns has it worked for you?
> > 
> > 
> > No it didn't work for me. Need to check with **crd.create** as **false** once.
> 
> Yes, please try with the false thing once and let me know you should run the command below for installing it:-
> 
> ` helm install t1 banzaicloud-stable/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2 --set crd.create=false`

should I need to use pravega/zookeeper-operator  or banzaicloud-stable/zookeeper-operator ?
`helm install t1 pravega/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2 --set crd.create=false`

**Comment by Prabhaker24** [comment] 2021-01-18 06:55
> > > > > I am installing in another namespace I can use the same release name right?
> > > > 
> > > > 
> > > > I always prefer to give a different helm release name. Have you tried giving the same release name in different ns has it worked for you?
> > > 
> > > 
> > > No it didn't work for me. Need to check with **crd.create** as **false** once.
> > 
> > 
> > Yes, please try with the false thing once and let me know you should run the command below for installing it:-
> > ` helm install t1 banzaicloud-stable/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2 --set crd.create=false`
> 
> should I need to use **pravega/zookeeper-operator** or **banzaicloud-stable/zookeeper-operator** ?
> `helm install t1 pravega/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2 --set crd.create=false`

you need to use  pravega/zookeeper-operator

**Comment by krishnachalla-hv** [comment] 2021-01-18 07:00
> > > > > > I am installing in another namespace I can use the same release name right?
> > > > > 
> > > > > 
> > > > > I always prefer to give a different helm release name. Have you tried giving the same release name in different ns has it worked for you?
> > > > 
> > > > 
> > > > No it didn't work for me. Need to check with **crd.create** as **false** once.
> > > 
> > > 
> > > Yes, please try with the false thing once and let me know you should run the command below for installing it:-
> > > ` helm install t1 banzaicloud-stable/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2 --set crd.create=false`
> > 
> > 
> > should I need to use **pravega/zookeeper-operator** or **banzaicloud-stable/zookeeper-operator** ?
> > `helm install t1 pravega/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2 --set crd.create=false`
> 
> you need to use pravega/zookeeper-operator

It worked with different release name but with same release it failed.
`helm install t1 pravega/zookeeper-operator -n tenant-1 --set watchnamespace=tenant-1 --set crd.create=true`
`helm install t1 pravega/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2 --set crd.create=false`
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "t1-zookeeper-operator" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "tenant-2": current value is "tenant-1"`
`helm install t0 pravega/zookeeper-operator -n tenant-2 --set watchnamespace=tenant-2 --set crd.create=false`

**Comment by Prabhaker24** [comment] 2021-01-18 07:58
no, it will not work with the same release name. You will have to have different release name.

**Comment by krishnachalla-hv** [comment] 2021-01-18 08:32
> no, it will not work with the same release name. You will have to have different release name.

If I say **--set crd.create=false** in the second tenant namespace then the zookeeper operator is local to that namespace? Can we have per tenant zookeeper operator?

**Comment by Prabhaker24** [comment] 2021-01-18 09:04
yes, but it basically means that each operator will be watching that namespace for the zookeeper resource.
yes, for all other tenant set the crd.create to false.

**Comment by krishnachalla-hv** [comment] 2021-01-18 10:04
Got It. Thank you. Is there any workaround to have same **release name** if we install it in different namespace?

**Comment by Prabhaker24** [comment] 2021-01-18 10:12
You're Welcome, no that's by design in helm we can't have more than one resource  with the same helm release name.

**Comment by Prabhaker24** [comment] 2021-01-18 10:35
@krishnachalla-hv, I am closing this issue. Feel free to comment here if you need any more help here.

**Closed by Prabhaker24** 2021-01-18 10:35 UTC
