### ISSUE TITLE
Deleting the zk pods/sts/CR and re-starting them later breaks reconcile, zookeeper remains unready

### ISSUE THREAD

**Issue by tmarcu** [pravega/zookeeper-operator#216] opened 2020-07-08 21:59 UTC
### Description

If the zookeeper statefulset is removed while keeping the PVC(s) intact, and then recreated later on the zookeeper CR will never become ready again. Errors from:
CR:
```
NAME             REPLICAS   READY REPLICAS   VERSION   DESIRED VERSION   INTERNAL ENDPOINT   EXTERNAL ENDPOINT   AGE
test-zookeeper   1          0                          0.2.7             ##.##.#.###:####    N/A                 63m

```

zookeeper-operator:
```
{"level":"error","ts":1594234921.6492033,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"zookeepercluster-controller","request":"green/test-zookeeper","error":"Error creating cluster metadata path /zookeeper-operator/test-zookeeper, Error creating parent zkNode: /zookeeper-operator: zk: node already exists","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.8/pkg/internal/controller/controller.go:215\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.8/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181126123746-eddba98df674/pkg/util/wait/wait.go:88"}
```

statefulset says that all the replicas are "ready" but the reconcile error above shows otherwise:
```
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: test-zookeeper-66c5bd5c84
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: test-zookeeper-66c5bd5c84
  updatedReplicas: 1
```

*Workaround which gets zk back up but I do not think is valid - you can delete the zk PVC and STS, and when it's all recreated again the zookeeper CR will report all the readyReplicas, but wiping the PVC removes some of the original bootstrapping data.

### Importance

Zookeeper runs as part of our cluster installation and one of the supported features is stopping the cluster (all pods/sts/CRs are removed), but the PVCs and application CRs remain so the components can be brought up again with the same data bindings.

### Location

_(Where is the piece of code, package, or document affected by this issue?)_ **internal**

### Suggestions for an improvement

The zookeeper operator should be able to re-register the restarted zk pods to the ensemble, and the readiness checks may need to be updated.

**Comment by anishakj** [comment] 2020-07-09 04:41
Can you please try with version `0.2.8-rc0`. I am not able to see the issue. Zookeeper cluster is coming up fine after deleting sts

**Comment by anishakj** [comment] 2020-08-06 04:55
Closing this  issue as we are not able to reproduce

**Closed by anishakj** 2020-08-06 04:55 UTC

**Comment by anxolerd** [comment] 2021-01-20 14:29
I have encountered the same issue while updating zookeeper operator to 0.2.9. The solution was to delete `/zookeeper-operator` path in zookeeper, using zkCli.sh from the zookeeper pod.

**Comment by vitalii-buchyn-exa** [comment] 2023-07-18 12:45
deleting path didn't work for me
after deletion it errors with like `Znode exists check failed for path`, so had to create a path manually, but initial error like `zk: node already exists` came back

zk operator version 2.0.14
