### ISSUE TITLE
Docker images are released with a wrong tag

### ISSUE THREAD

**Issue by adrianmo** [pravega/zookeeper-operator#65] opened 2019-05-14 14:22 UTC
Yesterday, @Tristan1900 and I released version 0.2.2. We created an operator release in GitHub, and then a [Travis build](https://travis-ci.org/pravega/zookeeper-operator/jobs/531865210) was triggered and [Docker images](https://cloud.docker.com/u/pravega/repository/docker/pravega/zookeeper-operator/tags) were created and pushed as part of the `deploy` stage. 

https://github.com/pravega/zookeeper-operator/blob/43a0bd70d1691693bb4cb1a198f9e36aaa0597b2/.travis.yml#L23

However, the image tag was formed incorrectly and the resulting image was pushed as `0.2.2-dirty` instead of `0.2.2`, making the release inaccessible through the expected tag. 

![Screenshot from 2019-05-14 16-01-37](https://user-images.githubusercontent.com/3786750/57704108-92e69100-7661-11e9-9baa-0e24927112dc.png)

Docker image tag is obtained through git tag information.

https://github.com/pravega/zookeeper-operator/blob/43a0bd70d1691693bb4cb1a198f9e36aaa0597b2/Makefile#L18

The above `git describe` command is using the `-dirty` flag, which adds the "-dirty" suffix to the git tag if the working tree has local modification.

That means that the Travis build process generates modifications that are not git-ignored. I was able to reproduce this locally and I found out that the `make dep` can make modifications to the `vendor` directory and the `Gopkg.lock` file that are causing `make build` to create images with the wrong tag. 

Two possible solutions to this are:

1. Remove the `-dirty` flag from the `git describe` command.
2. Add `Gopkg.lock` and `vendor` to the `.gitignore` file. Maybe we can also remove `Gopkg.lock` from the repo.

@Tristan1900 @spiegela what do you think?

**Comment by adrianmo** [comment] 2019-05-30 14:17
In the meantime, I have manually pushed the images with the corrected tags.

**Comment by Tristan1900** [comment] 2019-05-30 18:20
@adrianmo Thanks for the investigation! I think removing dirty flag seems easier. Indeed the Travis build is making changes, I think the dirty is caused by `skip_cleanup: true`. In the Pravega operator repo, make dep also changes the file sometimes but the change is cleaned up in the deploy stage. 
As you may notice, this repo does not contain `/vendor` file, the `/vendor` is generated during the build and used to build the docker image in the next stage. So I guess it is not possible to avoid a dirty working tree because `/vendor` has to be generated.

**Comment by adrianmo** [comment] 2019-05-31 08:23
@Tristan1900 sounds good to me. Let's remove the `--dirty` flag from the `git describe` command.

**Comment by anishakj** [comment] 2020-05-24 11:29
This is fixed with PR https://github.com/pravega/zookeeper-operator/pull/145

**Closed by anishakj** 2020-05-24 11:29 UTC
Labels: Priority-P4, bug
