### ISSUE TITLE
PVC are not deleted when ZK is deleted

### ISSUE THREAD

**Issue by adrianmo** [pravega/zookeeper-operator#42] opened 2019-01-17 12:12 UTC
When a `ZookeeperCluster` resource is deleted (i.e. `kubectl delete zk example`), PVC are not automatically deleted. PVC should have owner reference information so that they are attached to the CR lifecycle.

**Comment by spiegela** [comment] 2019-01-17 12:57
This is actually a feature of the StatefulSet-Set that creates the PVCs: https://kubernetes.io/docs/tasks/run-application/delete-stateful-set/#persistent-volumes

Kubernetes does not delete the PVCs for an STS to prevent accidental data loss and to cover scenarios when you want to recreate an STS.

If this functionality (deleting the PVC upon deletion of the ZK cluster) is required, then we could enable it through a feature flag — probably by implementing a finalizer. I don’t think this should be the _default_ behavior, though.

**Comment by spiegela** [comment] 2019-01-21 21:39
@adrianmo please, let me know if you think an optional finalizer is needed for deleting PVCs. If so, I'll rename this issue and keep it.

**Comment by adrianmo** [comment] 2019-01-22 08:30
@spiegela I don't think we need a finalizer. Setting the ownership reference to the PVC object should be enough to tie the PVC lifecycle to the CR object. 

This is how we do it in the Pravega operator: https://github.com/pravega/pravega-operator/blob/master/pkg/controller/pravegacluster/pravegacluster_controller.go#L252

The problem we were facing is that if a ZK cluster is deleted and recreated with the same name, it will fail to start. 

I'm OK with making it optional, however, if the default behavior is to preserve PVCs, we should be make sure those PVCs can be read.

**Comment by jkhalack** [comment] 2019-04-23 14:10
Any chance the new `VolumeReclaimPolicy` parameter will be implemented soon?

**Comment by bourgeoisor** [comment] 2019-04-24 15:07
While it is a feature of StatefulSets to not delete the PVC if or when the Pods gets deleted (for any reason), I don't think that explains why the PVC remains if the StatefulSet _itself_ is set to deletion.
In other words, I think this could just be fixed by adding owner refs to those PVC's, linking back to the ZookeeperCluster resource itself.
Deleting the Pods may be something we want to protect ourselves against (e.g. data loss prevention), but if specifically set the ZookeeperCluster to deletion, I don't see why we would carry the PVC around.
Thoughts?

**Comment by spiegela** [comment] 2019-04-24 19:29
Actually, it is also the case that if you delete a Kubernetes Stateful-Set the PVCs are still not deleted. This is by design to prevent the accidental loss of data.  In fact, there's an open issue in K8s SIG-Apps right now to look at ownership linking between PVCs and STS/Pods, but they have specifically elected _not_ to use owner-references, since deletion would trigger garbage collection of the PVCs.

Since this continues to the the default behavior of the STS, I don't think we should contradict that with our own default behavior.  I'm still good with implementing a `VolumeReclaimPolicy`, to have a non-default behavior for this as a finalizer, but I haven't had a chance to work on it myself.

**Closed** 2019-05-13 15:52 UTC
Labels: enhancement
