### ISSUE TITLE
Support configure annotations for zookeeper pod

### ISSUE THREAD

**Issue by qixiaogang** [pravega/zookeeper-operator#249] opened 2020-09-24 09:17 UTC
### Description

There is no way to configure the annotations of zookeeper pod

### Importance

Need to configure the annotations of zookeeper pod in our platform

### Location

Configure the annotations of .spec.pod.annotations, but check the zookeeper instance, annotations doesn't appear in the pod spec

### Suggestions for an improvement

Can we use .spec.pod.annotations to configure the zookeeper pod annotations?

**Comment by anishakj** [comment] 2020-09-24 12:55
This is a duplicate of https://github.com/pravega/zookeeper-operator/issues/125

**Closed** 2020-09-25 05:15 UTC

**Comment by qixiaogang** [comment] 2020-09-25 06:23
@anishakj  Do you have a plan to support annotations?
Or can I file a PR to support annotations?

**Comment by anishakj** [comment] 2020-09-25 06:40
Sure, Please go ahead

**Comment by qixiaogang** [comment] 2020-09-28 01:26
Thanks
