### ISSUE TITLE
zoo.cfg not getting modified.

### ISSUE THREAD

**Issue by gimpiron** [pravega/zookeeper-operator#224] opened 2020-08-06 09:42 UTC
### Description

Hey, so im trying to deploy zookeeper cluster with the following modification;
```
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "zookeeper"
spec:
  replicas: 3
  config:
    tickTime: 2000
    initLimit: 10
    syncLimit: 5
    clientPort: 2181
    maxClientCnxns: 2000
    maxSessionTimeout: 60000000
    autopurge.snapRetainCount: 3
    autopurge.purgeInterval: 1
    preAllocSize: 131072
    snapCount: 3000000
    reconfigEnabled: true
    4lw.commands.whitelist: "*"
    dataDir: "/data/zookeeper"
```

Sadly, i cannot see my changes inside my pod at /data/cong/zoo.cfg.
Morover, I cant see the changes the zookeeper configmap:

```
zoo.cfg:
----
4lw.commands.whitelist=cons, envi, conf, crst, srvr, stat, mntr, ruok
dataDir=/data
standaloneEnabled=false
reconfigEnabled=true
skipACL=yes
metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
metricsProvider.httpPort=7000
metricsProvider.exportJvmInfo=true
initLimit=10
syncLimit=5
tickTime=2000
quorumListenOnAllIPs=false
dynamicConfigFile=/data/zoo.cfg.dynamic
```

What am I missing? are all config options are configurable? 

### Importance

blocker

### Suggestions for an improvement

More documentation about possible options and where the config file is located & used.

**Comment by amuraru** [comment] 2020-08-06 19:15
Dupe of #222 ?

**Comment by gimpiron** [comment] 2020-08-09 07:05
@amuraru 
I took a look at your issue as well,
I am not sure its the same one, I cant find my changes at /conf/zoo.cfg aither.
Important to emphasize that I cant see my changes right from the first deployment of my yaml.

**Comment by anishakj** [comment] 2020-08-10 05:35
Currently all the config parameters we are not supporting in zoo.cfg, that is why you are not seeing it in first deployment. We will work on this enhancement soon.

**Comment by gimpiron** [comment] 2020-08-10 12:33
Ok, following! thanks for the answer

**Comment by pinkeshsharma** [comment] 2020-10-09 16:07
This is a blocker for us as well ...

**Comment by anishakj** [comment] 2020-10-22 05:52
Fixed by PR https://github.com/pravega/zookeeper-operator/pull/262

**Closed by anishakj** 2020-10-22 05:52 UTC
